# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pochak' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'

  pod 'Alamofire', '~> 5.2'

  pod 'Kingfisher', '~> 7.0'

  # Pods for pochak

  target 'pochakTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pochakUITests' do
    # Pods for testing
  end

end
